---
title: "AMH comments"
author: "Chris Beeley"
date: "22/11/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(echo = FALSE)

board <- pins::board_rsconnect()

trust_data <- pins::pin_read(board, "chrisbeeley/trustData") %>% 
  dplyr::filter(Date >= "2020-10-01" ,
                Date < "2021-09-30")

# load in team names and codes

team_info <- readr::read_csv("team_info.csv")

```

## Summary

Teams split three ways

* Community
* Crisis
* Inpatient

From Quarter 3 2020-21 to Q2 2021-22

## Community

```{r}

make_graph <- function(type){
  
  codes <- team_info %>% 
    filter(Type == type, !is.na(teamc))
  
  for_graph <- codes %>% 
    rowwise() %>% 
    mutate(Negative = trust_data %>% 
             filter(TeamC == teamc, 
                    !is.na(Imp_N1), 
                    Imp_N1 != "XN") %>% 
             nrow()) %>% 
    mutate(Positive = trust_data %>% 
             filter(TeamC == teamc, 
                    !is.na(Best_N1)) %>% 
             nrow())
  
  graph <- for_graph %>% 
    pivot_longer(cols = c(Complaints, Negative, Positive),
                 names_to = "Feedback") %>% 
    ggplot(aes(x = Name, y = value)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ Feedback, ncol = 1) + 
    theme(axis.text.x = element_text(angle = 70, hjust = 1, size = 10))
  
  graph %>% 
    ggsave(file = paste0(type, ".png"))
  
  graph %>% 
    ggsave(file = paste0(type, ".pdf"))
  
  return(graph)
  
}

make_graph("community")

```

## Inpatient

```{r}

make_graph("inpatient")

```

## Crisis

```{r}

make_graph("crisis")

```
